// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBARIKKqkQRPu5nwlIQHchWi5jT9SyJDhc',
    appId: '1:309416746937:web:f458b35fffb14293cca068',
    messagingSenderId: '309416746937',
    projectId: 'fast-chat-b7482',
    authDomain: 'fast-chat-b7482.firebaseapp.com',
    storageBucket: 'fast-chat-b7482.appspot.com',
    measurementId: 'G-7NWEKFCYSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUWTKMz6_47vwg4GnhdBn_4Ncingkbjg',
    appId: '1:309416746937:android:27b006d170d54054cca068',
    messagingSenderId: '309416746937',
    projectId: 'fast-chat-b7482',
    storageBucket: 'fast-chat-b7482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVSo-FC3JvYwtb_9vddzatzcXdcwkCH7o',
    appId: '1:309416746937:ios:fba6361c8ef945cbcca068',
    messagingSenderId: '309416746937',
    projectId: 'fast-chat-b7482',
    storageBucket: 'fast-chat-b7482.appspot.com',
    iosClientId: '309416746937-n9vaci8923nl56ci6mtmk3pqeoo55esn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVSo-FC3JvYwtb_9vddzatzcXdcwkCH7o',
    appId: '1:309416746937:ios:fba6361c8ef945cbcca068',
    messagingSenderId: '309416746937',
    projectId: 'fast-chat-b7482',
    storageBucket: 'fast-chat-b7482.appspot.com',
    iosClientId: '309416746937-n9vaci8923nl56ci6mtmk3pqeoo55esn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastChat',
  );
}
